# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - prod-ap-wolds-hr-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:  
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
  
      # Setup .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
          
      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore wolds-hr-api/wolds-hr-api.csproj
  
      # Build the project
      - name: Build with dotnet
        run: dotnet build wolds-hr-api/wolds-hr-api.csproj --configuration Release
  
      # Run unit tests with code coverage
      - name: Run tests with coverage
        run: |
          dotnet test wolds-hr-api.xunit/wolds-hr-api.xunit.csproj \
            --no-build \
            --configuration Release \
            --collect:"XPlat Code Coverage" \
            --results-directory ./TestResults
  
      # Generate coverage report (HTML)
      - name: Generate coverage report
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator \
            -reports:TestResults/**/coverage.cobertura.xml \
            -targetdir:coverage-report \
            -reporttypes:Html
  
      # Upload coverage report as artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report
  
      # Publish the app
      - name: dotnet publish
        run: dotnet publish wolds-hr-api/wolds-hr-api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
  
      # Upload published artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'prod-ap-wolds-hr-api'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D553457A9BF141058A55A3748812E1FC }}
  automated-api-tests:
      runs-on: ubuntu-latest
      needs: deploy
      steps:
        - uses: actions/checkout@v4
        - name: Install Postman CLI
          run: |
            curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
        - name: Login to Postman CLI
          run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
        - name: Create globals file from GitHub secret
          run: echo '${{ secrets.POSTMAN_GLOBALS_JSON }}' > globals.json
        - name: Run API tests
          run: |
            postman collection run "${{ github.workspace }}/PostmanCollections/WoldsHR.postman_collection.json" --globals globals.json -e "2cb1d520-705a-4860-befd-e7934ed11f8b" --integration-id "165236-${{ github.run_id }}" --env-var "upload_file=PostmanCollections/import-employees.csv"
            



