name: Build, Deploy and Test ASP.Net Core app - prod-ap-wolds-hr-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:  
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Setup .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      # 3️⃣ Restore dependencies
      - name: Restore dependencies
        run: dotnet restore wolds-hr-api/wolds-hr-api.csproj

      # 4️⃣ Build project
      - name: Build API
        run: dotnet build wolds-hr-api/wolds-hr-api.csproj --configuration Release

      # # 5️⃣ Run unit tests (optional: add coverage if desired)
      # - name: Run xUnit tests
      #   run: dotnet test wolds-hr-api.xunit/wolds-hr-api.xunit.csproj --configuration Release --no-build

      # 6️⃣ Publish API to ./publish folder
      - name: Publish API
        run: dotnet publish wolds-hr-api/wolds-hr-api.csproj -c Release -o ./publish

      # 7️⃣ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'prod-ap-wolds-hr-api'
          slot-name: 'Production'
          package: ./publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D553457A9BF141058A55A3748812E1FC }}

      # 8️⃣ Install Postman CLI
      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      # 9️⃣ Login to Postman CLI
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      # 🔟 Create globals file from GitHub secret
      - name: Create globals file
        run: echo '${{ secrets.POSTMAN_GLOBALS_JSON }}' > globals.json

      # 1️⃣1️⃣ Run Postman API tests
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/PostmanCollections/WoldsHR.postman_collection.json" \
            --globals globals.json \
            -e "2cb1d520-705a-4860-befd-e7934ed11f8b" \
            --integration-id "165236-${{ github.run_id }}" \
            --env-var "upload_file=PostmanCollections/import-employees.csv"

