name: Build, Deploy and Test ASP.Net Core app - prod-ap-wolds-hr-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:  
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Setup .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      # 3️⃣ Restore dependencies
      - name: Restore dependencies
        run: dotnet restore wolds-hr-api/wolds-hr-api.csproj

      # 4️⃣ Build project
      - name: Build API
        run: dotnet build wolds-hr-api/wolds-hr-api.csproj --configuration Release

      # 5️⃣ Publish API to ./publish folder
      - name: Publish API
        run: dotnet publish wolds-hr-api/wolds-hr-api.csproj -c Release -o ./publish

      # 6️⃣ Upload published folder as artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # 1️⃣ Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      # 2️⃣ Deploy the downloaded artifact
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'prod-ap-wolds-hr-api'
          slot-name: 'Production'
          package: ./.net-app
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D553457A9BF141058A55A3748812E1FC }}

  automated-api-tests:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4

      # 1️⃣ Install Postman CLI
      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      # 2️⃣ Login to Postman CLI
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      # 3️⃣ Create globals file from GitHub secret
      - name: Create globals file
        run: echo '${{ secrets.POSTMAN_GLOBALS_JSON }}' > globals.json

      # 4️⃣ Run Postman API tests
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/PostmanCollections/WoldsHR.postman_collection.json" \
            --globals globals.json \
            -e "2cb1d520-705a-4860-befd-e7934ed11f8b" \
            --integration-id "165236-${{ github.run_id }}" \
            --env-var "upload_file=PostmanCollections/import-employees.csv"
